check command return value in PS1

diff --git a/home_conf/bash_aliases b/home_conf/bash_aliases
--- a/home_conf/bash_aliases
+++ b/home_conf/bash_aliases
@@ -11,5 +11,28 @@ if [[ ${TMUX} ]]; then
 fi
 
 if [[ ! "${PATH}" == *${HOME}/bin* ]]; then
-  export PATH="$PATH:${HOME}/bin"
+	export PATH="$PATH:${HOME}/bin"
 fi
+
+# check command return value
+PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs
+
+__prompt_command() {
+	local EXIT="$?"				# This needs to be first
+
+	local RCol='\[\e[0m\]'
+
+	local BRed='\[\e[1;31m\]'
+	local BGre='\[\e[1;32m\]'
+	local BYel='\[\e[1;33m\]'
+	local BBlu='\[\e[1;34m\]'
+	local BPur='\[\e[1;35m\]'
+
+	PS1="${BGre}\u@\h${RCol}:${BBlu}\W${RCol}"
+
+	if [ $EXIT != 0 ]; then
+		PS1+="${BPur}\$ ${RCol}"	  # Add red if exit code non 0
+	else
+		PS1+="${BCol}\$ ${RCol}"
+	fi
+}
